### ISSUE TITLE
encoding of spaces

### ISSUE THREAD

**Issue by robjtede** [srph/gh-polls-web#2]
When the input has spaces, the markdown output has unencoded spaces which seem to not work with GitHub's markdown parser.

I assume this affects other URL encodable characters, as well.

**Comment by srph** [comment]
Having `  HAHAHA AH AH A HA%` as option makes `decodeURIComponent` throw `URIError: URI malformed`.

**Comment by srph** [comment]
Should be deployed within a minute. Feel free to re-open if you encounter this issue again.

Thanks!
