### ISSUE TITLE
Enhancement: Copy html code for polls

### ISSUE THREAD

**Issue by AndreiTelteu** [srph/gh-polls-web#3]
When you create a poll on [gh-polls.netlify.com](http://gh-polls.netlify.com) you have a button to copy the markdown code.
I think it would be useful to have an extra button to copy the **html code** (useful to paste in emails).

[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMCHH4T7KQ19J9K0NGN760ZD/Pro.%20Good%20idea)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMCHH4T7KQ19J9K0NGN760ZD/Pro.%20Good%20idea/vote)
[![](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMCHH4T7KQ19J9K0NGN760ZD/Con.%20Not%20useful)](https://m131jyck4m.execute-api.us-west-2.amazonaws.com/prod/poll/01BMCHH4T7KQ19J9K0NGN760ZD/Con.%20Not%20useful/vote)

**Comment by srph** [comment]
Sorry for the being unresponsive - been busy.

This should be easy to do as the markdown parser already provides this for us.

Will work on it as soon as I get my free time this week.
