### ISSUE TITLE
Pool options in github dark mode

### ISSUE THREAD

**Issue by rolivegab** [srph/gh-polls-web#5]
![image](https://user-images.githubusercontent.com/7359906/111035179-f9709d80-83f7-11eb-81ed-55a2620ca36d.png)

In dark mode, is near impossible to see pool option label.
Maybe there's a way to know if a user is using dark mode and change option color?

**Comment by 12rambau** [comment]
If you use the dimmed version it's even worse as the poll labels are simply invisble

**Comment by srph** [comment]
Hi folks, this seems like a very valid issue, but I would recommend going over to file this issue to https://github.com/apex/gh-polls. This codebase simply renders whichever the backend provides.
